name: build
on: [push, pull_request]
env:
  IPV6: 0
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc]
#       cc: [gcc, clang, g++, clang++]
#       target: [test, mip_test]
        target: [test]
        ssl: [OPENSSL]
#       ssl: [MBEDTLS, OPENSSL]
    name: linux ${{ matrix.target }} CC=${{ matrix.cc }} SSL=${{ matrix.ssl }}
    env:
      CC: ${{ matrix.cc }}
      SSL: ${{ matrix.ssl }}
    steps:
    - uses: actions/checkout@v3
    - run: ./test/setup_ga_network.sh
#   - run: sudo apt-get update ; sudo apt-get install libmbedtls-dev
    - run: make ${{ matrix.target }}
    - uses: codecov/codecov-action@v3
      with:
        gcov: true
        gcov_include: mongoose.c
